[package]
name = "interceptor"
version = "0.1.2"
authors = ["Rain Liu <yliu@webrtc.rs>"]
edition = "2018"
description = "A pure Rust implementation of Pluggable RTP/RTCP processors"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/interceptor"
homepage = "https://webrtc.rs"
repository = "https://github.com/webrtc-rs/interceptor"

[dependencies]
rtp = "0.3.4"
rtcp = "0.3.3"
srtp = { package = "webrtc-srtp", version = "0.4.0" }
async-trait = "0.1.42"
bytes = "1"
thiserror = "1.0.25"
anyhow = "1.0.41"
