[package]
name = "dtls"
version = "0.1.0"
authors = ["Rain Liu <yuliu@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
util = { path = "../util" }
transport = {path = "../transport"}
byteorder = "1.3.2"
lazy_static = "1.3.0"
p256 = "0.5.2"
p384 = "0.4.1"
rand = "0.7.3"
aes-gcm = "0.8.0"
ccm = "0.3.0"

[dev-dependencies]

