[workspace]
members = [
    "crates/dtls",
    "crates/ice",
    "crates/mdns",
    "crates/rtc",
    "crates/rtcp",
    "crates/rtp",
    "crates/sctp",
    "crates/sdp",
    "crates/srtp",
    "crates/stun",
    "crates/turn",
    "crates/util",
]

[profile.dev]
opt-level = 0