[workspace]
members = [
    "dtls",
    "ice",
    "rtc",
    "rtcp",
    "rtp",
    "sdp",
    "srtp",
    "stun",
    "turn",
    "util",
    "transport",
]

[profile.dev]
opt-level = 0