[package]
name = "webrtc"
version = "0.0.13"
authors = ["Rain Liu <yliu@webrtc.rs>"]
edition = "2018"
description = "A pure Rust implementation of WebRTC API"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/webrtc"
homepage = "https://webrtc.rs"
repository = "https://github.com/webrtc-rs/webrtc"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
util = { package = "webrtc-util", version = "0.4.2" }
sdp = "0.2.3"
mdns = { package = "webrtc-mdns", version = "0.3.3" }
stun = "0.3.3"
turn = "0.3.4"
ice = { package = "webrtc-ice", version = "0.4.0" }
dtls = { package = "webrtc-dtls", version = "0.4.11" }
rtp = "0.3.4"
rtcp = "0.3.3"
srtp = { package = "webrtc-srtp", version = "0.3.6" }
sctp = { package = "webrtc-sctp", version = "0.3.5" }
data = { package = "webrtc-data", version = "0.2.5" }
media = { package = "webrtc-media", version = "0.0.6" }
interceptor = "0.1.1"
tokio = { version = "1.10.1", features = ["full"] }
log = "0.4.14"
async-trait = "0.1.42"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8"
bytes = "1"
thiserror = "1.0.25"
anyhow = "1.0.41"
waitgroup = "0.1.2"
regex = "1"
url = "2.2.2"
rustls = { version = "0.19.0", features = ["dangerous_configuration"]}
rcgen = { version = "0.8.13", features = ["pem", "x509-parser"]}
ring = "0.16.19"
sha2 = "0.9.1"
chrono = "0.4.19"
base64 = "0.13.0"

[dev-dependencies]
tokio-test = "0.4"
env_logger = "0.8"
lazy_static = "1.4"
clap = "2"
hyper = { version = "0.14", features = ["full"] }
signal = {path = "examples/signal" }

[profile.dev]
opt-level = 0

[[example]]
name = "data-channels"
path = "examples/data-channels/data-channels.rs"
bench = false

[[example]]
name = "data-channels-close"
path = "examples/data-channels-close/data-channels-close.rs"
bench = false

[[example]]
name = "data-channels-create"
path = "examples/data-channels-create/data-channels-create.rs"
bench = false

[[example]]
name = "data-channels-detach"
path = "examples/data-channels-detach/data-channels-detach.rs"
bench = false

[[example]]
name = "data-channels-detach-create"
path = "examples/data-channels-detach-create/data-channels-detach-create.rs"
bench = false

[[example]]
name = "insertable-streams"
path = "examples/insertable-streams/insertable-streams.rs"
bench = false

[[example]]
name = "play-from-disk"
path = "examples/play-from-disk/play-from-disk.rs"
bench = false

[[example]]
name = "reflect"
path = "examples/reflect/reflect.rs"
bench = false

[[example]]
name = "rtp-forwarder"
path = "examples/rtp-forwarder/rtp-forwarder.rs"
bench = false

[[example]]
name = "save-to-disk"
path = "examples/save-to-disk/save-to-disk.rs"
bench = false

[[example]]
name = "ortc"
path = "examples/ortc/ortc.rs"
bench = false

[[example]]
name = "offer"
path = "examples/offer-answer/offer.rs"
bench = false

[[example]]
name = "answer"
path = "examples/offer-answer/answer.rs"
bench = false
