[package]
name = "webrtc"
version = "0.0.6"
authors = ["Rain Liu <yliu@webrtc.rs>"]
edition = "2018"
description = "A pure Rust implementation of WebRTC API"
license = "MIT"
documentation = "https://docs.rs/webrtc"
homepage = "https://webrtc.rs"
repository = "https://github.com/webrtc-rs/webrtc"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
util = { package = "webrtc-util", version = "0.2.4" }
sdp = "0.2.1"
mdns = { package = "webrtc-mdns", version = "0.2.14" }
stun = "0.2.4"
turn = "0.2.4"
ice = { package = "webrtc-ice", version = "0.2.4" }
dtls = { package = "webrtc-dtls", version = "0.2.4" }
rtp = "0.2.9"
rtcp = "0.2.4"
srtp = { package = "webrtc-srtp", version = "0.2.8" }
sctp = { package = "webrtc-sctp", version = "0.2.3" }
data = { package = "webrtc-data", version = "0.1.2" }
tokio = { version = "1.0", features = ["full"] }
log = "0.4.14"
async-trait = "0.1.42"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bytes = "1"
thiserror = "1.0.25"
anyhow = "1.0.41"

[dev-dependencies]
tokio-test = "0.4"
#env_logger = "0.8"
#chrono = "0.4.19"
#clap = "2"


[[example]]
name = "examples"
path = "examples/examples.rs"
bench = false
