[package]
name = "webrtc"
version = "0.0.6"
authors = ["Rain Liu <yliu@webrtc.rs>"]
edition = "2018"
description = "A pure Rust implementation of WebRTC API"
license = "MIT"
documentation = "https://docs.rs/webrtc"
homepage = "https://webrtc.rs"
repository = "https://github.com/webrtc-rs/webrtc"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
util = { package = "webrtc-util", version = "0.1.21" }
sdp = "0.1.5"
mdns = { package = "webrtc-mdns", version = "=0.2.10" }
stun = "0.1.17"
turn = "0.1.9"
ice = { package = "webrtc-ice", version = "0.1.9"} # path= "crates/ice"} #
dtls = {package = "webrtc-dtls", version = "0.1.6"} # path= "crates/dtls"} #
rtp = "=0.2.3"
rtcp = "=0.2.1"
srtp = { package = "webrtc-srtp", version = "=0.2.5"} #path = "crates/srtp"} #
sctp = { package = "webrtc-sctp", version = "0.1.0"}
#lazy_static = "1.3.0"
tokio = { version = "1.0", features = ["full"] }
#rand = "0.8.3"
log = "0.4.14"
async-trait = "0.1.42"
#waitgroup = "0.1.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bytes = "1"
thiserror = "1"
#rustls = { version = "0.19.0", features = ["dangerous_configuration"]}
#x509-parser = "0.9"

[dev-dependencies]
tokio-test = "0.4"
#env_logger = "0.8"
#chrono = "0.4.19"
#clap = "2"


[[example]]
name = "examples"
path = "examples/examples.rs"
bench = false
