[package]
name = "webrtc-media"
version = "0.0.6"
authors = ["Rain Liu <yliu@webrtc.rs>"]
edition = "2018"
description = "A pure Rust implementation of WebRTC Media API"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/webrtc-media"
homepage = "https://webrtc.rs"
repository = "https://github.com/webrtc-rs/media"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
util = { package = "webrtc-util", version = "0.4.2", default-features = false, features = ["marshal"] }
rtp = "0.3.4"
anyhow = "1.0.41"
byteorder = "1.4.3"
bytes = "1.0.1"
displaydoc = "0.2.1"
thiserror = "1.0.25"
rand = "0.8.4"

[dev-dependencies]
criterion = { version = "0.3.4", features = ["html_reports"] }
nearly_eq = "0.2.4"

[[bench]]
name = "audio_buffer"
harness = false
