[package]
name = "webrtc-util"
version = "0.4.0"
authors = ["Rain Liu <yliu@webrtc.rs>"]
edition = "2018"
description = "Utilities for WebRTC.rs stack"
license = "MIT"
documentation = "https://docs.rs/webrtc-util"
homepage = "https://webrtc.rs"
repository = "https://github.com/webrtc-rs/util"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["buffer", "conn", "ifaces", "vnet", "marshal"]
buffer = []
conn = ["buffer"]
ifaces = []
vnet = ["ifaces"]
marshal = []

[dependencies]
tokio = { version = "1.0", features = ["full"] }
lazy_static = "1.4"
async-trait = "0.1"
ipnet = "2.3.1"
log = "0.4.14"
rand = "0.8.4"
bytes = "1.0.1"
thiserror = "1.0.25"
anyhow = "1.0.41"

[target.'cfg(not(windows))'.dependencies]
nix = "0.8"
libc = "0.2.8"

[target.'cfg(windows)'.dependencies]
bitflags = "1.2.1"
winapi = "0.2.8"

[dev-dependencies]
tokio-test = "0.4"
env_logger = "0.8.3"
chrono = "0.4.19"
