[package]
name = "webrtc-rs-util"
version = "0.1.2"
authors = ["Rain Liu <yuliu@webrtc.rs>"]
edition = "2018"
description = "Utilities for WebRTC.rs stack"
license = "MIT"
documentation = "https://docs.rs/webrtc-rs-util"
homepage = "https://webrtc.rs"
repository = "https://github.com/webrtc-rs/util"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.1.0"
tokio = { version = "1.0", features = ["full"] }
aes-gcm = "0.8.0"
hmac = "0.10.1"
p256 = "0.7.1"
block-modes = "0.7.0"
x509-parser = "0.9"
der-parser = "5.0"
rcgen = "0.8.9"
lazy_static = "1.3.0"
ring = "0.16.19"
async-trait = "0.1"

[dev-dependencies]
tokio-test = "0.4"
