[package]
name = "webrtc-util"
version = "0.1.9"
authors = ["Rain Liu <yuliu@webrtc.rs>"]
edition = "2018"
description = "Utilities for WebRTC.rs stack"
license = "MIT"
documentation = "https://docs.rs/webrtc-util"
homepage = "https://webrtc.rs"
repository = "https://github.com/webrtc-rs/util"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.1.0"
tokio = { version = "1.0", features = ["full"] }
aes-gcm = "0.8.0"
hmac = "0.10.1"
p256 = "0.7.1"
block-modes = "0.7.0"
x509-parser = "0.9"
der-parser = "5.0"
rcgen = "0.8.9"
lazy_static = "1.3.0"
ring = "0.16.19"
async-trait = "0.1"
ipnet = "2.3.0"
log = "0.4.14"
rand = "0.8.3"

[target.'cfg(not(windows))'.dependencies]
nix = "0.8"
libc = "0.2.8"

[target.'cfg(windows)'.dependencies]
bitflags = "1.2.1"
winapi = "0.2.8"

[dev-dependencies]
tokio-test = "0.4"
env_logger = "0.8.3"
chrono = "0.4.19"

