[package]
name = "srtp"
version = "0.1.0"
authors = ["Rain Liu <yuliu@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
util = { path = "../util" }
rtp = { path = "../rtp" }
rtcp = { path = "../rtcp" }
byteorder = "1.3.2"
hmac = "0.7.1"
sha-1 = "0.8.1"
ctr = "0.3.2"
aes = "0.3.2"
subtle = "2.1.1"
lazy_static = "1.3.0"
tokio = "0.2.0-alpha.4"

[dev-dependencies]
tokio-test = "0.2.0-alpha.4"