[package]
name = "srtp"
version = "0.1.0"
authors = ["Rain Liu <yuliu@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
util = { path = "../util" }
byteorder = "1.3.2"
hmac = "0.7.1"
sha-1 = "0.8.1"
