[package]
name = "sdp"
version = "0.1.5"
authors = ["Rain Liu <yliu@webrtc.rs>"]
edition = "2018"
description = "A pure Rust implementation of SDP"
license = "MIT"
documentation = "https://docs.rs/sdp"
homepage = "https://webrtc.rs"
repository = "https://github.com/webrtc-rs/sdp"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.2.2"
rand = "0.8.4"
thiserror = "1.0.25"
anyhow = "1.0.41"
