[package]
name = "webrtc-rs-ice"
version = "0.0.1"
authors = ["Rain Liu <yuliu@webrtc.rs>"]
edition = "2018"
description = "A pure Rust implementation of ICE"
license = "MIT"
documentation = "https://docs.rs/webrtc-rs-ice"
homepage = "https://webrtc.rs"
repository = "https://github.com/webrtc-rs/ice"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
util = { package = "webrtc-rs-util", version = "0.1.5" }
mdns = { package = "webrtc-rs-mdns", version = "0.2.1" }
stun = { package = "webrtc-rs-stun", version = "0.1.13" }
turn = { package = "webrtc-rs-turn", version = "0.1.0" }
lazy_static = "1.3.0"
tokio = { version = "1.0", features = ["full"] }
url = "2.2.0"
crc32fast = "1.2.1"
uuid = { version = "0.8", features = ["v4"] }
rand = "0.8.3"
log = "0.4.14"

[dev-dependencies]
tokio-test = "0.4"
regex = "1.4.3"
crossbeam = "0.8.0"

[profile.dev]
opt-level = 0
