[package]
name = "webrtc-rtcp"
version = "0.2.0"
authors = ["Rain Liu <yliu@webrtc.rs>", "Michael Uti <utimichael9@gmail.com>"]
edition = "2018"
description = "A pure Rust implementation of RTCP"
license = "MIT"
documentation = "https://docs.rs/webrtc-rtcp"
homepage = "https://webrtc.rs"
repository = "https://github.com/webrtc-rs/rtcp"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.2"
bytes = "1"
lazy_static = "1.3.0"
thiserror = "1.0.23"
