[package]
name = "rtcp"
version = "0.1.0"
authors = ["Rain Liu <yuliu@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
util = { git = "https://github.com/webrtc-rs/util", branch = "main" }
byteorder = "1.3.2"
lazy_static = "1.3.0"