[package]
name = "util"
version = "0.1.0"
authors = ["Rain Liu <yuliu@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.1.0"
tokio = "0.2.0-alpha.4"
lazy_static = "1.3.0"

[dev-dependencies]
tokio-test = "0.2.0-alpha.4"