[package]
name = "util"
version = "0.1.0"
authors = ["Rain Liu <yuliu@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.1.0"
tokio = { version = "0.3", features = ["full"] }
aes-gcm = "0.8.0"

[dev-dependencies]
tokio-test = "0.3"