[package]
name = "webrtc-rs-turn"
version = "0.0.1"
authors = ["Rain Liu <yliu@webrtc.rs>"]
edition = "2018"
description = "A pure Rust implementation of TURN"
license = "MIT"
documentation = "https://docs.rs/webrtc-rs-turn"
homepage = "https://webrtc.rs"
repository = "https://github.com/webrtc-rs/turn"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
binaries = ["clap"]
default = ["binaries"]

[dependencies]
util = { package = "webrtc-rs-util", version = "0.1.4" }
stun = { package = "webrtc-rs-stun", version = "0.1.12" }
lazy_static = "1.3.0"
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"
clap = { version = "2", optional = true, default-features = false }
log = "0.4"
base64 = "0.13.0"
rand = "0.8.2"
ring = "0.16.19"
md5 = "0.7.0"

[dev-dependencies]
tokio-test = "0.4"
env_logger = "0.8"
hex = "0.4.2"

[[example]]
name = "turn_client_udp"
path = "examples/turn_client_udp.rs"
required-features = ["binaries"]
bench = false
