[package]
name = "hub"
version = "0.1.0"
edition = "2018"

[dependencies]
util = { path = "../../../util", package = "webrtc-util", default-features = false, features = [
    "conn"
] }
dtls = { path = "../../", package = "webrtc-dtls" }

tokio = { version = "1.15.0", features = ["full"] }
x509-parser = "0.12.0"
rcgen = { version = "0.8.13", features = ["pem", "x509-parser"] }
ring = "0.16.19"
rustls = "0.19.0"
log = "0.4"
thiserror = "1.0.25"
