[package]
name = "webrtc-rs-srtp"
version = "0.1.1"
authors = ["Rain Liu <yuliu@webrtc.rs>"]
edition = "2018"
description = "A pure Rust implementation of SRTP"
license = "MIT"
documentation = "https://docs.rs/webrtc-rs-srtp"
homepage = "https://webrtc.rs"
repository = "https://github.com/webrtc-rs/srtp"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
util = { package = "webrtc-rs-util", version = "0.1.1" }
rtp = { package = "webrtc-rs-rtp", version = "0.1.0" }
rtcp = { package = "webrtc-rs-rtcp", version = "0.1.0" }
byteorder = "1.3.2"
hmac = "0.10.1"
sha-1 = "0.9.1"
ctr = "0.6.0"
aes = "0.6.0"
subtle = "2.1.1"
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"
log = "0.4"
aead = "^0.3"
aes-gcm = "^0.8"

[dev-dependencies]
tokio-test = "0.4"
lazy_static = "^1.4"
