[package]
name = "webrtc-srtp"
version = "0.2.1"
authors = ["Rain Liu <yliu@webrtc.rs>"]
edition = "2018"
description = "A pure Rust implementation of SRTP"
license = "MIT"
documentation = "https://docs.rs/webrtc-srtp"
homepage = "https://webrtc.rs"
repository = "https://github.com/webrtc-rs/srtp"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
util = { package = "webrtc-util", version = "0.1.18" }
rtp = "0.2.2"
rtcp = "0.2.1"
byteorder = "1.3.2"
bytes = "1"
thiserror = "1"
hmac = { version = "0.10.1", features = ["std"] }
sha-1 = "0.9.1"
ctr = "0.6.0"
aes = "0.6.0"
subtle = "2.1.1"
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
log = "0.4"
aead = { version = "^0.3", features = ["std"] }
aes-gcm = "^0.8"

[dev-dependencies]
tokio-test = "0.4"
lazy_static = "^1.4"
