[workspace]
members = [
    "data",
    "dtls",
    "ice",
    "mdns",
    "media",
    "peer",
    "rtc",
    "rtcp",
    "rtp",
    "sctp",
    "sdp",
    "srtp",
    "stun",
    "turn",
    "util",
]

[profile.dev]
opt-level = 0
