[package]
name = "webrtc-rs-mdns"
version = "0.0.1"
authors = ["Rain Liu <yuliu@outlook.com>"]
edition = "2018"
description = "A pure Rust implementation of mDNS"
license = "MIT"
documentation = "https://docs.rs/webrtc-rs-mdns"
homepage = "https://webrtc.rs"
repository = "https://github.com/webrtc-rs/mdns"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
