[package]
name = "webrtc-rs-mdns"
version = "0.0.1"
authors = ["Rain Liu <yuliu@outlook.com>"]
edition = "2018"
description = "A pure Rust implementation of mDNS"
license = "MIT"
documentation = "https://docs.rs/webrtc-rs-mdns"
homepage = "https://webrtc.rs"
repository = "https://github.com/webrtc-rs/mdns"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
util = { package = "webrtc-rs-util", version = "0.1.2" }
lazy_static = "1.3.0"
tokio = { version = "1.0", features = ["full"] }
log = "0.4"


[dev-dependencies]
tokio-test = "0.4"
env_logger = "0.8"
chrono = "0.4.19"


[[example]]
name = "mdns_query"
path = "examples/mdns_query.rs"
bench = false


[[example]]
name = "mdns_server"
path = "examples/mdns_server.rs"
bench = false